In mvn-install-local remove the default for param 1 (version) and make it required

diff --git a/mvn-install-local b/mvn-install-local
--- a/mvn-install-local
+++ b/mvn-install-local
@@ -2,7 +2,8 @@
 rm -rf $HOME/.m2/repository/com/innoventsolutions/birt-spring-boot
 VERSION="$1"
 if [ -z "$VERSION" ]; then
-  VERSION="0.0.1-SNAPSHOT"
+  echo "missing parameter 1 (version)"
+  exit 1
 fi
 cd "$(dirname "${BASH_SOURCE[0]}")"
 echo "installing birt-spring-boot pom"
